services:
  postgres:
    container_name: postgres_temporary_chat
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    volumes:
      - temporary-chat-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=usr_temporary_chat
      - POSTGRES_PASSWORD=temporary_chat
      - POSTGRES_DB=temporary_chat

volumes:
  temporary-chat-db: